# Generated by Django 4.0.3 on 2022-04-09 14:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 9, 14, 11, 20, 700680, tzinfo=utc), editable=False),
        ),
    ]
